// <auto-generated />
namespace Lbl.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Couse_Content : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Couse_Content));
        
        string IMigrationMetadata.Id
        {
            get { return "201801291850183_Couse_Content"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
